### PR TITLE
Do not take `self` for `Value::is_*` methods.

### PR DESCRIPTION
**Pull request by xxchan**
Signed-off-by: xxchan <xxchan22f@gmail.com>

### CODE REVIEW

**Review by wangrunji0408 — APPROVED** [review]
LGTM

**Comment by wangrunji0408** [comment]
Could you help fix clippy and bump version to 0.1.5 by the way?

**Comment by wangrunji0408** [comment]
~~Why 0.2.0? I think it can be considered a bug fix. 🤡~~ IGNORE ME, published

**Comment by xxchan** [comment]
It’s a breaking change 🤡

**Pull request merged**
